// solid/src/routes/bench.tsx
/*
Copyright 2024 sby1ce

SPDX-License-Identifier: AGPL-3.0-or-later
*/

import { createResource, createSignal, type JSX } from "solid-js";
import {
  tsTimers as tsUpdate,
  type TimerFunc,
  type Origins,
} from "countdown-lib/timers";
import {
  initialize,
  seed,
  bench1000,
  formatBrowser,
} from "countdown-lib/bench";
import Button, { ButtonStyle } from "~/components/Button.tsx";
import styles from "~/scss/bench.module.scss";

interface Results {
  ts: number;
  rs: number;
}

function bench(
  setResults: (r: Results | null) => void,
  tsUpdate: TimerFunc,
  rsTimers: () => TimerFunc | undefined,
): void {
  const rsUpdate: TimerFunc | undefined = rsTimers();
  if (rsUpdate === undefined) {
    return;
  }

  const origins: Origins = seed();

  const tsAvg: number = bench1000(tsUpdate, origins);
  const rsAvg: number = bench1000(rsUpdate, origins);

  setResults({
    ts: tsAvg,
    rs: rsAvg,
  } satisfies Results);
}

export default function Bench(): JSX.Element {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const [rsUpdate, _yes] = createResource<TimerFunc, unknown>(initialize);

  const [results, setResults] = createSignal<Results | null>(null);

  const run: () => void = () => bench(setResults, tsUpdate, rsUpdate);

  return (
    <main class={styles.main}>
      <h1 class={styles.h1}>Benchmarks</h1>
      <p class={styles.p}>
        Average time over 1000 function runs in microseconds
      </p>

      <section class={styles.section}>
        <h2 class={styles.h2}>TypeScript</h2>
        <p class={styles.p}>{formatBrowser(results()?.ts)}</p>
      </section>
      <section class={styles.section}>
        <h2 class={styles.h2}>Rust</h2>
        <p class={styles.p}>{formatBrowser(results()?.rs)}</p>
      </section>

      <p class={styles.p}>Press the button to run the benchmark</p>

      <form class={styles.form}>
        <Button click={run} bg={ButtonStyle.SecondaryBg}>
          Benchmark
        </Button>
      </form>
    </main>
  );
}

// src/routes/bench/+page.svelte
<!-- 
Copyright 2024 sby1ce

SPDX-License-Identifier: AGPL-3.0-or-later
-->

<script lang="ts">
  import { onMount } from "svelte";
  import { tsTimers as tsUpdate, type Origins, type TimerFunc } from "$lib/timers.ts";
  import { initialize, seed, bench1000, formatBrowser } from "$lib/bench.ts";

  let rsUpdate: TimerFunc;

  onMount(async () => {
    rsUpdate = await initialize();
  });

  interface Results {
    ts: number;
    rs: number;
  }

  let results: Results | null = null;

  function bench(): void {
    const origins: Origins = seed();

    const tsAvg: number = bench1000(tsUpdate, origins);
    const rsAvg: number = bench1000(rsUpdate, origins);

    results = {
      ts: tsAvg,
      rs: rsAvg,
    } satisfies Results;
  }
</script>

<main>
  <h1>Benchmarks</h1>
  <p>Average time over 1000 function runs in microseconds</p>

  <section>
    <h2>TypeScript</h2>
    <p>{formatBrowser(results?.ts)}</p>
  </section>
  <section>
    <h2>Rust</h2>
    <p>{formatBrowser(results?.rs)}</p>
  </section>
</main>

{#if results === null}
  <p>Press the button to run the benchmark</p>
{/if}

<button type="button" on:click={bench}> Benchmark </button>
