// svelte/src/routes/TimerBlock.svelte
<!-- 
Copyright 2024 sby1ce

SPDX-License-Identifier: AGPL-3.0-or-later
-->

<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import {
    timers,
    tsTimers,
    wasmWrapper,
    type Origins,
    type TimerFunc,
    originsPipe,
  } from "$lib/timers.ts";
  import { storageAvailable } from "$lib/storage.ts";
  import Timer from "./Timer.svelte";
  import AddTimer from "./AddTimer.svelte";
  import Button, { ButtonStyle } from "$lib/Button.svelte";
  import init, { update_timers } from "../../../countdown-rs/pkg";

  let rsTimers: TimerFunc = () => {
    throw new Error("wasm failed to load");
  };
  let isRs: boolean = false;
  let updateTimers: TimerFunc = tsTimers;

  const switchFunc = (): void => {
    updateTimers = isRs ? tsTimers : rsTimers;
    isRs = !isRs;
  };

  function pop(id: number): void {
    timers.update((ts) => ts.slice(0, id).concat(ts.slice(id + 1)));

    if (storageAvailable("localStorage")) {
      localStorage.setItem("timers", JSON.stringify($timers));
    }
  }

  /* let formats = [
    {
      day: true,
      hour: true,
      minute: true,
      second: true,
    },
    {
      second: true,
    },
    {
      hour: true,
    },
  ]; */

  let origins: Origins = originsPipe($timers);
  $: {
    // during prerender this is undefined
    origins = originsPipe($timers);
  }

  let renders: string[][] = updateTimers(origins);
  const interval = setInterval(() => {
    renders = updateTimers(origins);
  }, 1000);

  async function initialize(): Promise<void> {
    try {
      await init();
      rsTimers = wasmWrapper(update_timers);
    } catch (e) {
      console.error(e);
    }
  }

  onMount(initialize);
  onDestroy(() => {
    clearInterval(interval);
  });
</script>

<div>
  <main>
    {#each $timers as timer, position (timer.key)}
      <Timer
        pop={pop.bind(null, position)}
        name={timer.name}
        countdowns={renders[position] ?? []}
      />
    {/each}
  </main>

  <aside>
    <p>
      Create a <strong>timer</strong> by setting its name and datetime
    </p>

    <article>
      <AddTimer />
    </article>

    <form>
      <Button style={ButtonStyle.SecondaryBg} on:click={switchFunc}>
        Switch {isRs ? "WA to JS" : "JS to WA"}
      </Button>
    </form>
  </aside>
</div>

<style lang="scss">
  @use "../lib/variables" as v;

  div {
    margin: 0;
    padding: 0;
    inline-size: 100%;
    display: grid;
    grid-template-columns: 4fr minmax(0, 1fr);
  }

  main {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  aside {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    border-left: 0.5em solid v.$primary-colour;
    display: flex;
    flex-direction: column;
    align-items: start;
  }

  @media (max-width: 400px) {
    div {
      grid-template-columns: 1fr;
    }
  }

  @mixin aside-item {
    height: min-content;
    padding: 1em;
    margin: 0;
  }

  p {
    @include aside-item;
  }

  article {
    @include aside-item;
    width: calc(100% - 2em);
    background-color: v.$secondary-bg-colour;
  }

  form {
    @include aside-item;
    width: calc(100% - 2em);
  }
</style>

// vue/src/components/TimerBlock.vue
<!-- 
Copyright 2024 sby1ce

SPDX-License-Identifier: AGPL-3.0-or-later
-->

<script setup lang="ts">
import { computed, onBeforeMount, onUnmounted, ref } from "vue";
import {
  tsTimers,
  wasmWrapper,
  type Origins,
  type TimerFunc,
  originsPipe,
  useTimers,
} from "~/timers.ts";
import Timer from "~/components/Timer.vue";
import AddTimer from "~/components/AddTimer.vue";
import Button from "~/components/Button.vue";
import { ButtonStyle } from "~/utils.ts";
import init, { update_timers } from "../../../countdown-rs/pkg";

const isInitialized = ref(false);
const rsTimers = ref<TimerFunc>(() => {
  throw new Error("wasm failed to load");
});
const isRs = ref(false);
const updateTimers = ref<TimerFunc>(tsTimers);

async function initialize(): Promise<void> {
  if (isInitialized.value) {
    return;
  }
  try {
    await init();
    rsTimers.value = wasmWrapper(update_timers);
  } catch (e) {
    console.error(e);
  }
  isInitialized.value = true;
}

async function switchFunc(): Promise<void> {
  // Different behaviour from other
  // because background async loading is not supported
  await initialize();
  updateTimers.value = isRs.value ? tsTimers : rsTimers.value;
  isRs.value = !isRs.value;
}

const timers = useTimers();

const origins = computed<Origins>(() => originsPipe(timers.inner));
const renders = ref<string[][]>(updateTimers.value(origins.value));

let interval: ReturnType<typeof setInterval>;
onBeforeMount(() => {
  interval = setInterval(() => {
    renders.value = updateTimers.value(origins.value);
  }, 1000);

  timers.init();
});
onUnmounted(() => {
  clearInterval(interval);
});
</script>

<template>
  <div>
    <main>
      <ClientOnly>
        <Timer
          v-for="(timer, position) in timers.inner"
          :key="timer.key"
          :name="timer.name"
          :countdowns="renders.at(position) ?? []"
          @pop="() => timers.pop(position)"
        />
      </ClientOnly>
    </main>

    <aside>
      <p>Create a <strong>timer</strong> by setting its name and datetime</p>

      <article>
        <AddTimer />
      </article>

      <form>
        <Button :color="ButtonStyle.SecondaryBg" @click="switchFunc">
          Switch {{ isRs ? "WA to JS" : "JS to WA" }}
        </Button>
      </form>
    </aside>
  </div>
</template>

<style lang="scss" scoped>
@use "../scss/variables" as v;

div {
  margin: 0;
  padding: 0;
  inline-size: 100%;
  display: grid;
  grid-template-columns: 4fr minmax(0, 1fr);
}

main {
  display: flex;
  flex-direction: column;
  align-items: center;
}

aside {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  border-left: 0.5em solid v.$primary-colour;
  display: flex;
  flex-direction: column;
  align-items: start;
}

@media (max-width: 400px) {
  div {
    grid-template-columns: 1fr;
  }
}

@mixin aside-item {
  height: min-content;
  padding: 1em;
  margin: 0;
}

p {
  @include aside-item;
}

article {
  @include aside-item;
  width: calc(100% - 2em);
  background-color: v.$secondary-bg-colour;
}

form {
  @include aside-item;
  width: calc(100% - 2em);
}
</style>
